name: tox

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    shell: sh

jobs:
  cibuildwheel:
    strategy:
      matrix:
        os:
          - name: "Linux"
            type: "ubuntu-latest"
          - name: "macOS"
            type: "macos-latest"
          - name: "Windows"
            type: "windows-latest"

    name: tox / ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.type }}

    steps:
      - name: Get source
        uses: actions/checkout@v3
        with:
          submodules: true

      - # Required to run job via act: https://github.com/nektos/act
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "./requirements-ci.txt"
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11

      - # Required to run job via act: https://github.com/nektos/act
        name: Setup dependencies
        run: pip install -r "./requirements-ci.txt"

      - name: Test
        run: pipx run tox
